title: Learnin
author:  beendra
email: alexandra.ricardel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning about GitHub pages.
 
theme: minima

# social links
twitter_username: yrgalal_ # DO NOT include the @ character, or else the build will fail!
github_username:  beendra # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
